CREATE DATABASE DATA_DIGGER;

USE DATA_DIGGER;

CREATE TABLE CUSTOMERS(
  CUSTOMER_ID INT PRIMARY KEY,
  NAME VARCHAR(30),
  EMAIL VARCHAR(200),
  ADDRESS VARCHAR(200)
)

--INSERT DATA
INSERT INTO CUSTOMERS(CUSTOMER_ID,NAME,EMAIL,ADDRESS)
VALUES
(1, 'Aapj Patel', 'aapj.patel@example.com', 'Ahmedabad, Gujarat, India'),
(2, 'Rohan Sharma', 'rohan.sharma@example.com', 'Delhi, India'),
(3, 'Priya Iyer', 'priya.iyer@example.com', 'Chennai, Tamil Nadu, India'),
(4, 'Arjun Singh', 'arjun.singh@example.com', 'Lucknow, Uttar Pradesh, India'),
(5, 'Meera Desai', 'meera.desai@example.com', 'Rajkot, Gujarat, India');


--RETRIVE ALL CUSTOMER DETAILS
SELECT * FROM CUSTOMERS;

--UPDATE A CUSTOMER ADDRESS
UPDATE CUSTOMERS
SET ADDRESS = 'Jaipur, Rajsthan'
WHERE CUSTOMER_ID = 1;

--DELETE A CUSTOMER USING TJEIR CUSTOMER_ID
DELETE FROM CUSTOMERS
WHERE CUSTOMER_ID = 2;

--DISPLAY ALL CUSTOMER WHOSE NAME IS 'ALICE'
SELECT * FROM CUSTOMERS
WHERE NAME = 'ALICE';



CREATE TABLE ORDERS(
    ORDER_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    ORDERDATE DATE,
    TOTALAMOUNT INT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
)

--INSERT DATA
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDERDATE, TOTALAMOUNT)
VALUES
(101, 1, '2026-03-01', 2500),
(102, 2, '2026-03-05', 1800),
(103, 3, '2026-03-10', 3200),
(104, 4, '2026-03-15', 1500),
(105, 5, '2026-03-20', 2700);

--RETRIEVE ALL ORDERS MADE BY A SPECIFIC CUSTOMER
SELECT * FROM ORDERS
WHERE CUSTOMER_ID = 4;

--UPDATE AN ORDER'S TOTAL AMOUNT
UPDATE ORDERS
SET TOTALAMOUNT = 3000
WHERE ORDER_ID = 101;

--DELETE AN ORDER USING ITS ORDER_ID
DELETE FROM ORDERS
WHERE ORDER_ID = 102;

--RETRIEVE ORDERS PLACED IN THE LAST 30 DAYS
SELECT * FROM ORDERS
WHERE ORDERDATE >= DATE_SUB(CURDATE(),INTERVAL 30 DAY);

--RETRIEVE THE HIGEST,LOWEST AND AVERAGE ORDER AMOUNT USING AGGREGATE FUNCTION
SELECT 
    MAX(TOTALAMOUNT) AS HIGHEST_AMOUNT,
    MIN(TOTALAMOUNT) AS LOWEST_AMOUNT,
    AVG(TOTALAMOUNT) AS AVERAGE_AMOUNT
FROM ORDERS;


CREATE TABLE PRODUCTS(
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCTNAME VARCHAR(30),
    PRICE DECIMAL(8,2),
    STOCK INT
)

--INSERT DATA
INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCTNAME, PRICE, STOCK)
VALUES
(201, 'Laptop', 55000.00, 25),
(202, 'Smartphone', 22000.00, 50),
(203, 'Headphones', 1500.00, 100),
(204, 'Tablet', 18000.00, 30),
(205, 'Smartwatch', 7000.00, 40);


--RETRIEVE ALL PRODUCTS AORTED BY PRICE IN DESCENDING ORDER
SELECT * FROM PRODUCTS
ORDER BY PRICE DESC;

--UPDATE PRICE OF A SPECIFIC PRODUCCT
UPDATE PRODUCTS
SET PRICE = 10000.00
WHERE PRODUCT_ID = 205;

--DELEE PRODUCT IF IT'S OUT OF STOCK
DELETE FROM PRODUCTS
WHERE STOCK = 0;

--RETRIEVE PRODUCTS WHOSE PRICE IS BETWEEN RS.500 AND RS.2000
SELECT PRODUCTNAME,PRICE FROM PRODUCTS
WHERE PRICE BETWEEN 500 AND 2000;


--RETRIVE THE MOST EXPENSIVE AND CHEPEST PRODUCT USIGN MAX() AND MIN().
SELECT 
    MAX(PRICE) AS EXPENSIVE_PRODUCT,
    MIN(PRICE) AS CHEPEST_PRODUCT
FROM PRODUCTS;


CREATE TABLE ORDER_DETAIL(
    ORDER_DETAIL_ID INT PRIMARY KEY,
    ORDER_ID INT,
    PRODUCT_ID INT,
    QUANTITY INT,
    SUB_TOTAL DECIMAL(8,2),
    FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
)

-- INSERT DATA
INSERT INTO ORDER_DETAIL (ORDER_DETAIL_ID, ORDER_ID, PRODUCT_ID, QUANTITY, SUB_TOTAL)
VALUES
(1001, 101, 201, 1, 55000.00),   
(1002, 102, 202, 2, 44000.00),   
(1003, 103, 203, 3, 4500.00),    
(1004, 104, 204, 1, 18000.00),   
(1005, 105, 205, 2, 14000.00);  


--RETRIEVE ALL ORDER DETAILS FOR A SPECIFIC ORDER
SELECT * FROM ORDER_DETAIL
WHERE ORDER_DETAIL_ID = 1001;

--CALCULATE THE TOTAL REVENUE GENERATED FROM ALL ORDERS USING SUM().
SELECT SUM(SUB_TOTAL) AS REVENUE FROM ORDER_DETAIL;

--RETRIVE THE TOP 3 MOST ORDERD PRODUCTS.
SELECT PRODUCT_ID , SUM(QUANTITY) AS TOTAL_QUANTITY
FROM ORDER_DETAIL
GROUP BY PRODUCT_ID
ORDER BY TOTAL_QUANTITY DESC
LIMIT 3;

--COUNT HOW MANY TIMES A SPECIFIC PRODUCT HAS BEEN SOLD USING COUNT()
SELECT COUNT(*) AS TIME_SOLD FROM ORDER_DETAIL
WHERE PRODUCT_ID = 201;

