CREATE DATABASE FINAL_PROJECT;
USE FINAL_PROJECT;

CREATE TABLE DEPARTMENTS(
    DEPARTMENT_ID INT PRIMARY KEY,
    DEPARTMENT_NAME VARCHAR(100)
);

CREATE TABLE COURSES(
    COURSE_ID INT PRIMARY KEY,
    COURSE_NAME VARCHAR(100),
    DEPARTMENT_ID INT,
    CREDITS INT,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID)
);

CREATE TABLE INSTRUCTORS(
    INSTRUCTOR_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100),
    DEPARTMENT_ID INT,
    FOREIGN KEY (DEPARTMENT_ID) REFERENCES DEPARTMENTS(DEPARTMENT_ID)
);

CREATE TABLE STUDENTS(
    STUDENT_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100),
    BIRTH_DATE DATE,
    ENROLLMENT_DATE DATE
);

CREATE TABLE ENROLLMENTS(
    ENROLLMENT_ID INT PRIMARY KEY,
    STUDENT_ID INT,
    COURSE_ID INT,
    ENROLLMENT_DATE DATE,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENTS(STUDENT_ID),
    FOREIGN KEY (COURSE_ID) REFERENCES COURSES(COURSE_ID)
);

-- 1.PERFORM CRUD OPERATIONS ON THE TABLES.

-- DEPARTMENTS DATA
INSERT INTO DEPARTMENTS (DEPARTMENT_ID, DEPARTMENT_NAME) VALUES
(1, 'Computer Science'),
(2, 'Mathematics'),
(3, 'Physics'),
(4, 'Literature'),
(5, 'History'),
(6, 'Biology'),
(7, 'Chemistry'),
(8, 'Economics'),
(9, 'Philosophy'),
(10, 'Engineering');

-- COURSES DATA
INSERT INTO COURSES (COURSE_ID, COURSE_NAME, DEPARTMENT_ID, CREDITS) VALUES
(101, 'Database Systems', 1, 4),
(102, 'Algorithms', 1, 3),
(103, 'Operating Systems', 1, 4),
(201, 'Calculus I', 2, 4),
(202, 'Linear Algebra', 2, 3),
(203, 'Statistics', 2, 3),
(301, 'Quantum Mechanics', 3, 4),
(302, 'Classical Mechanics', 3, 4),
(401, 'World Literature', 4, 3),
(402, 'Modern Poetry', 4, 2),
(501, 'Ancient History', 5, 3),
(601, 'Genetics', 6, 4),
(602, 'Microbiology', 6, 4),
(701, 'Organic Chemistry', 7, 4),
(801, 'Macroeconomics', 8, 3),
(901, 'Ethics', 9, 2),
(1001, 'Civil Engineering Basics', 10, 4);

-- INSTRUCTORS DATA
INSERT INTO INSTRUCTORS (INSTRUCTOR_ID, FIRST_NAME, LAST_NAME, EMAIL, DEPARTMENT_ID) VALUES
(1, 'Alice', 'Johnson', 'alice.johnson@university.edu', 1),
(2, 'Bob', 'Smith', 'bob.smith@university.edu', 2),
(3, 'Carol', 'Davis', 'carol.davis@university.edu', 3),
(4, 'David', 'Miller', 'david.miller@university.edu', 4),
(5, 'Eva', 'Clark', 'eva.clark@university.edu', 5),
(6, 'Frank', 'White', 'frank.white@university.edu', 6),
(7, 'Grace', 'Hall', 'grace.hall@university.edu', 7),
(8, 'Henry', 'Young', 'henry.young@university.edu', 8),
(9, 'Ivy', 'King', 'ivy.king@university.edu', 9),
(10, 'Jack', 'Wright', 'jack.wright@university.edu', 10);

-- STUDENTS DATA
INSERT INTO STUDENTS (STUDENT_ID, FIRST_NAME, LAST_NAME, EMAIL, BIRTH_DATE, ENROLLMENT_DATE) VALUES
(1001, 'Emma', 'Brown', 'emma.brown@student.edu', '2002-05-14', '2021-09-01'),
(1002, 'Liam', 'Wilson', 'liam.wilson@student.edu', '2001-11-23', '2020-09-01'),
(1003, 'Olivia', 'Taylor', 'olivia.taylor@student.edu', '2003-02-10', '2022-09-01'),
(1004, 'Noah', 'Anderson', 'noah.anderson@student.edu', '2002-07-30', '2021-09-01'),
(1005, 'Sophia', 'Martinez', 'sophia.martinez@student.edu', '2001-03-12', '2020-09-01'),
(1006, 'James', 'Thomas', 'james.thomas@student.edu', '2002-09-18', '2021-09-01'),
(1007, 'Isabella', 'Harris', 'isabella.harris@student.edu', '2003-01-25', '2022-09-01'),
(1008, 'Benjamin', 'Clark', 'benjamin.clark@student.edu', '2002-06-05', '2021-09-01'),
(1009, 'Mia', 'Lewis', 'mia.lewis@student.edu', '2001-12-14', '2020-09-01'),
(1010, 'Lucas', 'Walker', 'lucas.walker@student.edu', '2003-04-22', '2022-09-01');

-- ENROLLMENTS DATA
INSERT INTO ENROLLMENTS (ENROLLMENT_ID, STUDENT_ID, COURSE_ID, ENROLLMENT_DATE) VALUES
(1, 1001, 101, '2021-09-05'),
(2, 1001, 201, '2021-09-06'),
(3, 1002, 102, '2020-09-07'),
(4, 1002, 202, '2020-09-08'),
(5, 1003, 301, '2022-09-08'),
(6, 1003, 401, '2022-09-09'),
(7, 1004, 402, '2021-09-09'),
(8, 1005, 501, '2020-09-10'),
(9, 1006, 601, '2021-09-11'),
(10, 1007, 701, '2022-09-12'),
(11, 1008, 801, '2021-09-13'),
(12, 1009, 901, '2020-09-14'),
(13, 1010, 1001, '2022-09-15');

-- READ: RETRIVE ALL DATA
SELECT * FROM STUDENTS;
SELECT * FROM DEPARTMENTS;
SELECT * FROM COURSES;
SELECT * FROM INSTRUCTORS;
SELECT * FROM ENROLLMENTS;

-- UPDATE: UPDATE IN ALL TABLES
UPDATE DEPARTMENTS 
SET DEPARTMENT_NAME = 'Computer Engineering'
WHERE DEPARTMENT_ID = 1;

UPDATE COURSES
SET CREDITS = 5
WHERE COURSE_ID = 101;

UPDATE INSTRUCTORS
SET LAST_NAME = 'Johnson-Smith'
WHERE INSTRUCTOR_ID = 1;

UPDATE STUDENTS
SET EMAIL = 'emma.newemail@student.edu'
WHERE STUDENT_ID = 1001;

UPDATE ENROLLMENTS
SET ENROLLMENT_DATE = '2021-09-10'
WHERE ENROLLMENT_ID = 1;

-- DELETE: DELETE SOME RECORDS
DELETE FROM INSTRUCTORS
WHERE INSTRUCTOR_ID = 10;

DELETE FROM DEPARTMENTS
WHERE DEPARTMENT_ID = 5;

-- 2. RETRIEVE STIDENTS WHO ENROLLED AFTER 2022.
SELECT FIRST_NAME, LAST_NAME, EMAIL FROM STUDENTS
WHERE ENROLLMENT_DATE > '2022-01-01';

-- 3. RETRIEVE COURSES OFFERED BY THE MATHEMATICS DEPARTMENT WITH A LIMIT OF 5 COURSES.
SELECT COURSE_NAME, CREDITS
FROM COURSES
WHERE DEPARTMENT_ID=(
    SELECT DEPARTMENT_ID
    FROM DEPARTMENTS
    WHERE DEPARTMENT_NAME = 'MATHEMATICS'
) 
LIMIT 5;

-- 4. GET THE NUMBER OF STUDENTS ENROLL IN EACH COURSE, FILTERING FOR COURSES WITH MORE THAN 5 STUDENTS.
SELECT COURSE_ID, COUNT(STUDENT_ID) AS NUM_STUDENTS
FROM ENROLLMENTS
GROUP BY COURSE_ID
HAVING COUNT(STUDENT_ID) > 5;

-- 5. FIND STUDENTS WHO ARE ENROLLED IN BOTH INSTRUCTION TO SQL AND DATA STRUCTURES.
SELECT FIRST_NAME, LAST_NAME, EMAIL
FROM STUDENTS
WHERE STUDENT_ID IN(
    SELECT STUDENT_ID
    FROM ENROLLMENTS
    WHERE COURSE_ID = (
        SELECT COURSE_ID
        FROM COURSES
        WHERE COURSE_NAME = 'Database Systems'
        AND COURSE_NAME = 'Data Structures'
    )
);

-- 6. FIND STUDENTS WHO ARE EITHER ENROLLED IN INSTRUCTION TO SQL OR DATA STRUCTURES.
SELECT FIRST_NAME, LAST_NAME, EMAIL
FROM STUDENTS
WHERE STUDENT_ID IN(
    SELECT STUDENT_ID
    FROM ENROLLMENTS
    WHERE COURSE_ID = (
        SELECT COURSE_ID
        FROM COURSES
        WHERE COURSE_NAME = 'Database Systems'
        OR COURSE_NAME = 'Data Structures'
    )
);

-- 7. CALCULATE THE AVERAGE NUMBER OF CREDITS FOR ALL COURSES.
SELECT AVG(CREDITS) AS AVERAGE_CREDITS
FROM COURSES;

-- 8. FIND MAXIMUM SALARY OF INSTRUCTIORS IN THE COMPUTER SCIENCE DEPARTMENT.
ALTER TABLE INSTRUCTORS
ADD SALARY DECIMAL(10,2);

UPDATE INSTRUCTORS SET SALARY = 75000 WHERE INSTRUCTOR_ID = 1; 
UPDATE INSTRUCTORS SET SALARY = 68000 WHERE INSTRUCTOR_ID = 2; 
UPDATE INSTRUCTORS SET SALARY = 72000 WHERE INSTRUCTOR_ID = 3; 
UPDATE INSTRUCTORS SET SALARY = 65000 WHERE INSTRUCTOR_ID = 4; 
UPDATE INSTRUCTORS SET SALARY = 60000 WHERE INSTRUCTOR_ID = 5; 
UPDATE INSTRUCTORS SET SALARY = 70000 WHERE INSTRUCTOR_ID = 6; 
UPDATE INSTRUCTORS SET SALARY = 71000 WHERE INSTRUCTOR_ID = 7; 
UPDATE INSTRUCTORS SET SALARY = 69000 WHERE INSTRUCTOR_ID = 8;
UPDATE INSTRUCTORS SET SALARY = 64000 WHERE INSTRUCTOR_ID = 9;

SELECT MAX(SALARY) AS MAX_SALARY
FROM INSTRUCTORS
WHERE DEPARTMENT_ID = (
    SELECT DEPARTMENT_ID
    FROM DEPARTMENTS
    WHERE DEPARTMENT_NAME = 'Statistics'
);

-- 9. COUNT THE NUMBER OF STUDENTS ENROLLED IN EACH DEPARTMENT.
SELECT d.DEPARTMENT_NAME, COUNT(DISTINCT s.STUDENT_ID) AS TOTAL_STUDENTS
FROM STUDENTS s
JOIN ENROLLMENTS e ON s.STUDENT_ID = e.STUDENT_ID
JOIN COURSES c ON e.COURSE_ID = c.COURSE_ID
JOIN DEPARTMENTS d ON c.DEPARTMENT_ID = d.DEPARTMENT_ID
GROUP BY d.DEPARTMENT_NAME;

-- 10. INNER JOIN: RETRIEVE STUDENTS AND THEIR CORRESPONDIND COURSES.
SELECT s.FIRST_NAME,
     s.LAST_NAME, 
     c.COURSE_NAME
FROM STUDENTS s
LEFT JOIN ENROLLMENTS e 
ON s.STUDENT_ID = e.STUDENT_ID
LEFT JOIN COURSES c 
ON e.COURSE_ID = c.COURSE_ID;

-- 11. LEFT JOIN: RETRIEVE ALL STUDENTS AND THEIR CORRESPONDING COURSES, IF ANY.
SELECT s.FIRST_NAME,
    s.LAST_NAME,
    c.COURSE_NAME
FROM STUDENTS s
LEFT JOIN COURSES c
ON s.STUDENT_ID = c.COURSE_ID;

-- 12. SUBQUERY: FIND STUDENTS ENROLLED IN COURSES THAT HAE MORE THAN 10 STUDENTS.
SELECT FIRST_NAME,
    LAST_NAME,
    EMAIL
FROM STUDENTS
WHERE STUDENT_ID IN(
    SELECT STUDENT_ID
    FROM ENROLLMENTS
    WHERE COURSE_ID IN(
        SELECT COURSE_ID
        FROM ENROLLMENTS
        GROUP BY COURSE_ID
        HAVING COUNT(STUDENT_ID) > 10
    )
);

-- 13. EXTRACT THE YEAR FROM THE ENROLLMENT_DATE OF STUDENTS.
SELECT FIRST_NAME,
    LAST_NAME,
    YEAR(ENROLLMENT_DATE) AS EnrollmentYear
FROM STUDENTS;

-- 14. CONCATENATE THE INSTRUCTORS FIRST AND LAST NAME.
SELECT FIRST_NAME,
     LAST_NAME, 
     CONCAT(FIRST_NAME, ' ' ,LAST_NAME) AS FULL_NAME
FROM INSTRUCTORS;

-- 15. CALCULATE THE RUNNIG TOTAL OF STUDENTS ENROLLED IN COURSES.
SELECT INSTRUCTOR_ID,
       SALARY,
       SUM(SALARY) 
       OVER (ORDER BY INSTRUCTOR_ID) AS RUNNING_TOTAL
FROM INSTRUCTORS;

-- 16. LABLE STUDENTS AS 'SENIOR' OR 'JUNIOR' BASED ON THEIR YEAR OF ENROLLMENT(IF THE ENROLLDATE IS MORE THAN 4 YEARS FROM THE CURRENTDATE, PUT THE LABLE 'SENIOR' OTHERWISE 'JUNIOR').
SELECT FIRST_NAME,
    LAST_NAME,
    ENROLLMENT_DATE,
    CASE
        WHEN DATEDIFF(CURRENT_DATE,ENROLLMENT_DATE) > 1460 THEN 'SENIOR'
        ELSE 'JUNIOR'
    END AS STUDENT_LEVEL
FROM STUDENTS;