CREATE DATABASE DATA_TRANSFORMER;
USE DATA_TRANSFORMER;

CREATE TABLE CUSTOMERS(
    CUSTOMER_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50),
    LAST_NAME VARCHAR(50),
    EMAIL VARCHAR(100),
    REGISTRATION_DATE DATE
);

CREATE TABLE ORDERS(
    ORDER_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    ORDER_DATE DATE,
    TOTAL_AMOUNT DECIMAL(10,2),
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID)
);

CREATE TABLE EMPLOYEES(
    EMPLOYEE_ID INT PRIMARY KEY,
    FIRST_NAME VARCHAR(50), 
    LAST_NAME VARCHAR(50),
    DEPARTMENT VARCHAR(50),
    HIRE_DATE DATE,
    SALARY DECIMAL(10,2)
);

-- Insert  customers
INSERT INTO CUSTOMERS (CUSTOMER_ID, FIRST_NAME, LAST_NAME, EMAIL, REGISTRATION_DATE) VALUES
(1, 'Amit', 'Shah', 'amit.shah@example.com', '2023-01-15'),
(2, 'Priya', 'Mehta', 'priya.mehta@example.com', '2023-02-10'),
(3, 'Rahul', 'Patel', 'rahul.patel@example.com', '2023-03-05'),
(4, 'Sneha', 'Joshi', 'sneha.joshi@example.com', '2023-04-20'),
(5, 'Vikas', 'Rao', 'vikas.rao@example.com', '2023-05-12'),
(6, 'Neha', 'Kapoor', 'neha.kapoor@example.com', '2023-06-01'),
(7, 'Arjun', 'Desai', 'arjun.desai@example.com', '2023-07-18'),
(8, 'Meera', 'Singh', 'meera.singh@example.com', '2023-08-25'),
(9, 'Karan', 'Malhotra', 'karan.malhotra@example.com', '2023-09-09'),
(10, 'Ritika', 'Verma', 'ritika.verma@example.com', '2023-10-30'),
(11, 'Suresh', 'Nair', 'suresh.nair@example.com', '2023-11-15'),
(12, 'Anjali', 'Gupta', 'anjali.gupta@example.com', '2023-12-05');

-- Insert orders
INSERT INTO ORDERS (ORDER_ID, CUSTOMER_ID, ORDER_DATE, TOTAL_AMOUNT) VALUES
(101, 1, '2023-02-01', 2500.00),
(102, 2, '2023-02-15', 1800.50),
(103, 3, '2023-03-10', 3200.75),
(104, 4, '2023-04-25', 1500.00),
(105, 5, '2023-05-20', 2750.25),
(106, 6, '2023-06-15', 4000.00),
(107, 7, '2023-07-22', 2200.00),
(108, 8, '2023-08-30', 3100.50),
(109, 9, '2023-09-12', 1450.00),
(110, 10, '2023-10-31', 5000.00),
(111, 11, '2023-11-20', 2800.75),
(112, 12, '2023-12-10', 3600.00);

-- Insert employees
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, DEPARTMENT, HIRE_DATE, SALARY) VALUES
(201, 'Rohan', 'Kumar', 'Sales', '2022-01-10', 45000.00),
(202, 'Pooja', 'Sharma', 'HR', '2022-02-15', 40000.00),
(203, 'Deepak', 'Yadav', 'IT', '2022-03-20', 60000.00),
(204, 'Anita', 'Reddy', 'Finance', '2022-04-25', 55000.00),
(205, 'Sanjay', 'Bose', 'Marketing', '2022-05-30', 48000.00),
(206, 'Kavita', 'Iyer', 'Sales', '2022-06-12', 47000.00),
(207, 'Manish', 'Chopra', 'IT', '2022-07-18', 62000.00),
(208, 'Divya', 'Nanda', 'Finance', '2022-08-22', 53000.00),
(209, 'Rajesh', 'Pillai', 'HR', '2022-09-05', 41000.00),
(210, 'Sunita', 'Das', 'Marketing', '2022-10-10', 49000.00),
(211, 'Ajay', 'Singhania', 'Sales', '2022-11-15', 46000.00),
(212, 'Leena', 'George', 'IT', '2022-12-20', 61000.00);

-- QUERIES TO PERFORM

-- 1. INNER JOIN: RETRIVE ALL ORDERS AND CUSTOMER DETAILS WHERE ORDER EXISTS.
SELECT O.ORDER_ID, 
    O.ORDER_DATE, 
    O.TOTAL_AMOUNT, 
    C.FIRST_NAME, 
    C.LAST_NAME, 
    C.EMAIL 
FROM ORDERS O
INNER JOIN CUSTOMERS C 
ON O.CUSTOMER_ID = C.CUSTOMER_ID;

-- 2. LEFT JOIN: RETRIVE ALL CUSTOMERS AND THEIR ORDERS IF ANY.
SELECT C.FIRST_NAME, 
    C.LAST_NAME, 
    O.ORDER_ID, 
    O.ORDER_DATE, 
    O.TOTAL_AMOUNT
FROM CUSTOMERS C
LEFT JOIN ORDERS O 
ON C.CUSTOMER_ID = O.CUSTOMER_ID;

-- 3. RIGHT JOIN: RETRIVE ALL ORDERS AND THEIR CUSTOMER DETAILS IF ANY.
SELECT O.ORDER_ID, 
    O.ORDER_DATE, 
    O.TOTAL_AMOUNT, 
    C.FIRST_NAME, 
    C.LAST_NAME
FROM ORDERS O
RIGHT JOIN CUSTOMERS C
ON O.CUSTOMER_ID = C.CUSTOMER_ID;

-- 4. FULL OUTER JOIN: RETRIVE ALL CUSTOMERS AND THEIR ORDERS , REGARDLESS OF MATCHING.
SELECT C.FIRST_NAME,
     C.LAST_NAME, 
     O.ORDER_ID, 
     O.ORDER_DATE, 
     O.TOTAL_AMOUNT
FROM CUSTOMERS C
LEFT JOIN ORDERS O 
ON C.CUSTOMER_ID = O.CUSTOMER_ID
UNION
SELECT C.FIRST_NAME,
     C.LAST_NAME, 
     O.ORDER_ID, 
     O.ORDER_DATE, 
     O.TOTAL_AMOUNT
FROM CUSTOMERS C
RIGHT JOIN ORDERS O 
ON C.CUSTOMER_ID = O.CUSTOMER_ID;

-- 5. SUBQUERY TO FIND CUSTOMERS WHO HAVE PLACED ORDERS WOTH MORE THAN THE AVERAGE AMOUNT.
SELECT FIRST_NAME,
     LAST_NAME, 
     EMAIL
FROM CUSTOMERS
WHERE CUSTOMER_ID IN(
    SELECT CUSTOMER_ID
    FROM ORDERS
    WHERE TOTAL_AMOUNT >(SELECT AVG(TOTAL_AMOUNT) FROM ORDERS)
);

-- 6. SUBQUERY TO FIND EMPLOYEES WITH SALARIES ABOVE THE AVERAGE SALRY.
SELECT FIRST_NAME, 
    LAST_NAME,
    DEPARTMENT, 
    SALARY
FROM EMPLOYEES
WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEES);

-- 7. EXTRACT THE YEAR AND MONTH FROM THE ORDERDATE.
SELECT 
    ORDER_ID,
    CUSTOMER_ID,
    YEAR(ORDER_DATE) AS OrderYear,
    MONTHNAME(ORDER_DATE) AS OrderMonth
FROM ORDERS;

-- 8. CALCULATE THR DIFFRECE IN DAYS BETWEEN TWO DATES (ORDER DATE AND CURRENT DATE).
SELECT
    ORDER_ID,
    ORDER_DATE,
    DATEDIFF(CURRENT_DATE,ORDER_DATE) AS DAYS_SINCE_ORDER
FROM ORDERS;

-- 9. FORMAT THE ORDER_DATE TO A MORE READABLE FORMAT (E.G., 'DD-MON-YYYY').
SELECT ORDER_ID,
    ORDER_DATE,
    DATE_FORMAT(ORDER_DATE, '%d-%b-%Y') AS FORMATTED_ORDER_DATE
FROM ORDERS;

-- 10. CONCATENATE FIRST_NAME AND LAST_NAME TO FORM A FULL NAME.
SELECT FIRST_NAME,
    LAST_NAME,
    CONCAT(FIRST_NAME, ' ', LAST_NAME) AS FULL_NAME
FROM CUSTOMERS;

-- 11. REPLACE PART OF STRING(E.G. REPLACE 'JOHN' WITH 'JONATHAN' IN FIRST_NAME).
SELECT FIRST_NAME,
    LAST_NAME,
    REPLACE(FIRST_NAME, 'Amit', 'Amitabh') AS UPDATED_FIRST_NAME
FROM CUSTOMERS;

-- 12. CONVERT FIRST_NAME TO UPPERCASE AND LAST_NAME TO LOWERCASE.
SELECT FIRST_NAME,
    LAST_NAME,
    UPPER(FIRST_NAME) AS FIRST_NAME_UPPER,
    LOWER(LAST_NAME) AS LAST_NAME_LOWER
FROM CUSTOMERS;

-- 13. TRIM EXTRA SPACES FROM THE EMAIL FEILD.
SELECT EMAIL,
    TRIM(EMAIL) AS TRIMMED_EMAIL
FROM CUSTOMERS;

-- 14. CALCULATE THE RUNNING TOTAL OF TOTALAMOUNTFPR EACH ORDER.
SELECT ORDER_ID,
    ORDER_DATE,
    TOTAL_AMOUNT,
    SUM(TOTAL_AMOUNT) OVER (ORDER BY ORDER_DATE) AS RUNNING_TOTAL
FROM ORDERS;

-- 15. RANK ORDERS BASED ON TOTALAMOUNT USING THE RANK() FUNCTION.
SELECT ORDER_ID,
    ORDER_DATE,
    TOTAL_AMOUNT,
    RANK() OVER (ORDER BY TOTAL_AMOUNT ) AS ORDER_RANK
FROM ORDERS;

-- 16. ASSIGN A DISCOUNT BASED ON TOTAL_AMOUNT IN ORDERS(E.G >1000:10%OF , >500:5% OFF).
SELECT ORDER_ID,
    ORDER_DATE,
    TOTAL_AMOUNT,
    CASE
        WHEN TOTAL_AMOUNT > 500 THEN TOTAL_AMOUNT * 0.05
        WHEN TOTAL_AMOUNT > 1000 THEN TOTAL_AMOUNT * 0.10
        ELSE 0
    END AS DISCOUNT
FROM ORDERS;

-- 17. CATEGORIZE EMPLOYEES SALARIES AS HIGH MEDIUM OR LOW.
SELECT FIRST_NAME,
    LAST_NAME,
    SALARY,
    CASE
        WHEN SALARY > 60000 THEN 'HIGH'
        WHEN SALARY > 40000 THEN 'MEDIUM'
        ELSE 'LOW'
    END AS SALARY_CATEGORY
FROM EMPLOYEES;